import org.rookout.files.Utilities
import org.rookout.testsUtil.TestUtilities

def label = "worker-${UUID.randomUUID().toString()}"
def testsNames = null

podCreator.initMain(label: label) {
    node(label) {
        print(pwd())
        container('rookout-helm') {
            def myRepo = checkout scm
            env.GIT_BRANCH = myRepo.GIT_BRANCH.replaceAll('/|_', '-')
            def testFolder = "regression-test"
            stage('Creating tests and building docker files') {
                def scriptToUse = libraryResource 'generate_tests.groovy'
                def jobName = "tutorial-ruby"
                def dockerTag = TestUtilities.getDockerTagNameForRegression(testFolder, jobName)
                withCredentials([
                        string(credentialsId: 'ROOKOUT_REGGRESION_TOKEN', variable: 'ROOKOUT_TOKEN')
                ]) 
                sh("docker build . -t ${dockerTag} && gcloud docker -- push ${dockerTag}")
                TestUtilities.createTest(this, scriptToUse, jobName, pwd() + "/.jenkins", "Jenkinsfile.test", testFolder)

            }
            if ("master".equals(env.GIT_BRANCH)) {
                stage('Run ruby tests') {
                    triggerer.regressionEx(GIT_BRANCH: "master", GIT_REPO: "ruby-sdk", LANGUAGE_TO_RUN: "ruby") {

                    }
                }
            }
        }
    }
}